# DEMO Trading accounts' configs
fx_choice_demo:
  path: C:\Users\James Ockhuis\AppData\Roaming\FXChoice MetaTrader 5\terminal64.exe
  login: 714093
  password: mrazi4ky
  server: FXChoice-MetaTrader 5 Pro

hfm_demo:
  path: C:\Program Files\HotForex MetaTrader 5 Terminal\terminal64.exe
  login: 57011683
  password: VYxEb%%s&
  server: HFMarketsSA1-Demo2


# LIVE small/test accounts
hfm_live_micro:
  path: C:\Program Files\HotForex MetaTrader 5 Terminal\terminal64.exe
  login: 54012076
  password: jKjyGRe%%
  server: HFMarketsSA1-Demo2

vault_markets_live_usd:
  path: C:\Program Files (x86)\VaultMarkets MT4 Terminal\terminal.exe
  login: 218928
  password: oclJTT3T
  server: VaultMarkets-Live01

